### ISSUE TITLE
[Question] How would one allow the container to run non-interactively and output the result to a file?

### ISSUE THREAD

**Issue by Nite16** [leplusorg/docker-hash#147]
### Feature description

```markdown
I would like to let the container run for a period time and output the result to a file for later review. For example running with -d flag.
```

**Comment by thomasleplus** [comment]
Hi @Nite16,

Good question, I would have thought that something like this would work (where `myfile` is the file that you want to hash in the current directory):

`docker run --rm -d --user="$(id -u):$(id -g)" --net=none -v "$(pwd):/tmp" leplusorg/hash sh -c 'sha256sum /tmp/myfile > /tmp/myfile.sha'`

But then I tested it and it doesn't, the file `myfile.sha` doesn't get created in the mounted folder. Interestingly enough, if I remove the `--rm` to keep the container after it exits, and remove the redirection:

`docker run -d --user="$(id -u):$(id -g)" --net=none -v "$(pwd):/tmp" leplusorg/hash sh -c 'sha256sum /tmp/myfile'`

Then the `docker logs` command shows my that the hash is being computed and sent to the standard output. So the issue resides in the `>` pipe redirection somehow.

Let me think about this some more.

Cheers,

Tom

**Comment by thomasleplus** [comment]
Actually this doeswork, I don't know what confused me earlier: 

`docker run -d --rm --user="$(id -u):$(id -g)" --net=none -v "$(pwd):/tmp" leplusorg/hash sh -c 'sha256sum /tmp/myfile > /tmp/myfile.sha'`

**Comment by Nite16** [comment]
Just tried this, it's working great. Thanks for the help! I've been a long-time user of your containers from prior to them being under leplusorg; they're wonderful. Cheers!
